mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/',include('polls.urls',namespace='polls')),
]

polls/urls.py
#coding=utf-8
from django.conf.urls import url
from . import views
urlpatterns=[
    url(r'^$',views.index,name='index'),
    url(r'^(?P<question_id>[0-9]+)/details/$',views.details,name='details'),
    url(r'^(?P<question_id>[0-9]+)/vote/$',views.vote,name='vote'),
    url(r'^(?P<question_id>[0-9]+)/results/$',views.results,name='results'),

    ]

polls/models.py
#coding=utf-8
from __future__ import unicode_literals
from django.utils import timezone
from django.db import models
import datetime
# Create your models here.
class Question(models.Model):
    question_text=models.CharField(max_length=200,verbose_name='问题')
    pub_date=models.DateTimeField(verbose_name='日期')
    
    def  was_published_recently(self):
        now=timezone.now()
        return now>=self.pub_date >=now - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __str__(self):
        return self.question_text
class Choice(models.Model):
    question=models.ForeignKey(Question,verbose_name='问题')
    choice_txt=models.CharField(max_length=200,verbose_name="答案")
    votes=models.IntegerField(default=0,verbose_name='投票量')
    def __str__(self):
        return self.choice_txt
    

polls/views.py
#coding=utf-8
from django.shortcuts import render
from django.http import HttpResponse,Http404,HttpResponseRedirect                                    #1
from .models import Question ,Choice
from  django.template import RequestContext,loader #1
from  django.shortcuts import render,get_object_or_404
from django.core.urlresolvers import reverse
from  django.views import generic
from django.utils import timezone
# Create your views here.

def index(request):
    list_question_text=Question.objects.filter(pub_date__lte=timezone.now()).order_by('pub_date')[:6]
    context={'list_question_text':list_question_text}
    return render(request,'polls/index.html',context)

def details(request,question_id):
    question = get_object_or_404(Question.objects.filter(pub_date__lte=timezone.now()),pk=question_id)
    return render(request, 'polls/details.html',{'question':question})

def vote(request, question_id):
    q = get_object_or_404(Question, pk=question_id)
    try:
        select_choice = q.choice_set.get(pk=request.POST['choice'])
    except (KeyError,Choice.DoesNotExist):
        return  render(request,'polls/details.html',{'question':q,'error_message':'you did not choice'})
    else:
        select_choice.votes+=1;
        select_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(q.id,)))


def results(request,question_id):
     question=get_object_or_404(Question,pk=question_id)
     return render(request,'polls/results.html',{'question':question})

polls/templates/polls/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> polls details</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
   <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
    <label for="choice{{ forloop.counter }}">{{ choice.choice_txt }}</label> <br/>
{% endfor %}
    <input type="submit" value="投票">
</form>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>polls  demo</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"/>
</head>
<body>
{% if list_question_text %}
    <ul>
       {% for question in list_question_text %}
           <li><a href="{% url 'polls:details' question.id %}">{{ question.question_text }}</a></li>
       {% endfor %}
    </ul>

{% else %}
    <p> not available</p>
{% endif %}
</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>polls results</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_txt }}----->{{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>
<a href="{% url 'polls:details' question.id %}">Vote again?</a>
</body>
</html>